name: Set up Python
description: Install Python and Armarium development dependencies.
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - run: python -m pip install -e '.[dev]'
      shell: bash
